image: maven:3-jdk-8

build:
  script: "mvn clean package"
  artifacts:
    name: "VelocityLobbyPlugin"
    paths: 
    - "target/*.jar"


include:
  template: Dependency-Scanning.gitlab-ci.yml

include:
  template: SAST.gitlab-ci.yml